package Config;

import org.openqa.selenium.By;

public class Locators {

  public static final By USERNAME = By.id("inputUsername");
  public static final By PASSWORD = By.id("inputPassword");
  public static final By LOGIN_BTN = By.tagName("button");
  public static final By LINK_QA = By.xpath("//span[normalize-space(text())='QA Measures']");
  public static final By CHOOSE_FACILITY = By.id("facilityList");
  public static final By SELECT_FACILITY = By.xpath("(//div[@class='fs-09'])[1]");
  public static final By HOME_SUBMIT_BTN = By.xpath("//div[@class='facility-center d-flex']//button[1]");
  public static final By OR_TOGGLE = By.id("orProvider");
  public static final By OB_TOGGLE = By.id("obProvider");
  public static final By OR_LABEL = By.id("orShift");
  public static final By OB_LABEL = By.id("obShift");
  public static final By ADD_CASE_OR_SITE = By.id("addCaseValue");
  public static final By ADD_CASE_OB_SITE = By.id("addCaseValue");
  public static final By ADD_CASE_CLOSE_BTN = By.cssSelector("button.close-button[aria-label='Close']");
  public static final By TRANSFER_CASE = By.id("transferCase");
  public static final By TRANSFER_CLOSE_BTN = By.xpath("//h5[text()='Available Cases']/following-sibling::button");
  public static final By ADD_SHIFT = By.id("addShift");
  public static final By PROVIDER_INPUT = By.id("providerInput");
  public static final By PROVIDER_DROPDOWN = By.xpath("//div[@id='dynamicProviderList']//li[1]");
  public static final By PROCEDURE_INPUT = By.id("procedureInput");
  public static final By PROCEDURE_DROPDOWN = By.xpath("//ul[@id='procedureDropdown']//li[1]");
  public static final By POSITION_INPUT = By.id("positionInput");
  public static final By POSITION_DROPDOWN = By.xpath("//ul[@id='positionDropdown']//li[2]");
  public static final By FROM_DATE_INPUT = By.id("fromDateInput");
  public static final By TO_DATE_INPUT = By.id("toDateInput");
  public static final By ADD_BTN = By.id("modalAddBtn");
  public static final By CLEAR_BTN = By.id("modalClearBtn");
  public static final By ADD_SHIFT_CLOSE_BTN = By.id("closeModal");
  public static final By PREVIOUS_BTN = By.id("prevBtn");
  public static final By NEXT_BTN = By.id("nextBtn");
  public static final By MONTH_VIEW_BTN = By.id("monthViewBtn");
  public static final By WEEK_VIEW_BTN = By.id("weekViewBtn");
  public static final By DAY_VIEW_BTN = By.id("dayViewBtn");
  public static final By ALL_TOGGLE = By.id("changeprovider");
  public static final By GAS_FILTER = By.xpath("(//div[contains(@class,'col-2 col-sm-3')]//button)[2]");
  public static final By FILTER_FACILITY_DROPDOWN = By.id("facilityFilterInput-ts-control");
  public static final By FILTER_PROVIDER_DROPDOWN = By.id("providerFilterInput-ts-control");
  public static final By FACILITY_DROPDOWN_CLEAR_BTN = By.xpath("(//div[@class='ts-control']//div)[2]");
  public static final By PROVIDER_DROPDOWN_CLEAR_BTN = By.xpath("(//div[@class='ts-control']//div)[3]");
  public static final By FILTER_CLEAR_BTN = By.id("filterClearBtn");
  public static final By FILTER_CLOSE_BTN = By.xpath("//h5[text()='Filters']/following-sibling::button");
  public static final By MORE_SHIFT = By.xpath("(//div[contains(@class,'event shift-border-purple')]/following-sibling::div)[2]");
  public static final By BACK_BTN = By.xpath("(//div[contains(@class,'col-2 col-sm-3')]//button)[1]");
  public static final By BATCH = By.id("batchQuality");
  public static final By BATCH_FACILITY = By.id("batchProcedureLocation");
  public static final By BATCH_SUBMIT_BTN = By.id("multiQaSubmitButton");
  public static final By BATCH_CLOSE_POPUP = By.xpath("//h5[text()='Batch Quality']/following-sibling::button");
  public static final By EMPTY_SHIFT = By.id("shiftConfirmation");
  public static final By EMPTY_SHIFT_SELECT = By.id("emptyShiftFacility");
  public static final By EMPTY_SHIFT_CLEAR = By.id("emptyShiftClear");
  public static final By EMPTY_CLOSE = By.id("closeModel");
  public static final By OTHERS = By.id("otherSection");
  public static final By GAS_CALENDAR = By.id("addShiftLink");
  public static final By GAS_SHIFT = By.id("GasShifts");
  public static final By FROM_SHIFT = By.id("fromShift");
  public static final By TO_SHIFT = By.id("toShift");
  public static final By GAS_FACILITIES = By.id("facilities");
  public static final By SHIFT_DROPDOWN = By.id("shifts");
  public static final By GAS_SHIFT_CLOSE_BTN = By.xpath("//div[@id='mySchedule']/div[1]/div[1]/div[1]/button[1]/span[1]");
  public static final By GAS_SUBMIT = By.id("findSchedule");
  public static final By GAS_CLEAR = By.id("upcomingClearBtn");
  public static final By GAS_HISTORY = By.id("GasHistory");
  public static final By TRANSFER_TAB = By.linkText("Transfer History");
  public static final By PAGINATION_NUMBER = By.linkText("2");
  public static final By PREVIOUS_LINK = By.linkText("Previous");
  public static final By SWAP_TAB = By.linkText("Swap History");
  public static final By SHARE_TAB = By.linkText("Share History");
  public static final By QA_TAB = By.linkText("QA History");
  public static final By MISSING_QA_TAB = By.linkText("Missing QA");
  public static final By GAS_HISTORY_BACK_BTN = By.xpath("//a[@class='back-button']//button[1]");
  public static final By GLOBAL_CASE = By.id("global");
  public static final By ORGANIZATION_DROP = By.id("organization");
  public static final By GLOBAL_FACILITY = By.id("facility");
  public static final By GLOBAL_SITE = By.id("globalSite");
  public static final By GLOBAL_SURGEON = By.id("globalSurgeon");
  public static final By GLOBAL_SURGEON_DROPDOWN = By.id("globalSurgeon-dropdown-list");
  public static final By GLOBAL_SUBMIT_BTN = By.id("globalAllCase");
  public static final By GLOBAL_CLEAR_BTN = By.id("clearButton");
  public static final By GLOBAL_CLOSE_BTN = By.xpath("//div[@id='globalCase']/div[1]/div[1]/div[1]/button[1]/span[1]");
  public static final By PEEL_OFF_ORDER = By.id("todayGoHomeListLink");
  public static final By ORDER_FACILITY = By.id("facilitySearch");
  public static final By ORDER_FACILITY_DROP = By.xpath("//ul[@id='facilityListData']//li[contains(text(),'BANNER IRONWOOD MEDICAL CENTER')]");
  public static final By SEARCH_DATE = By.id("searchDate");
  public static final By ORDER_SUBMIT = By.id("submitDate");
  public static final By ORDER_BACK_BTN = By.xpath("//div[@class='d-flex justify-content-end']//a[1]");
  // Not OB Case locators
  public static final By NOT_OB_FIRST_NAME = By.id("notObFirstName");
  public static final By NOT_OB_LAST_NAME = By.id("notObLastName");
  public static final By NOT_OB_GENDER = By.id("notObGender");
  public static final By NOT_OB_FACILITY_DROP = By.id("notObProcedureLocationAddField");
  public static final By NOT_OB_OPTION = By.id("notObOption");
  public static final By NOT_OB_SERVICE = By.id("notObService");
  public static final By NOT_OB_SITE = By.id("notObSite");
  public static final By NOT_OB_DOB = By.id("notObDob");
  public static final By NOT_OB_SAVE_BUTTON = By.xpath("//*[@id=\"notOBNewCaseAdd\"]/div/div/div[3]/button[3]");
  public static final By NOT_OB_UPLOAD_BUTTON = By.xpath("//*[@id=\"notOBNewCaseAdd\"]/div/div/div[3]/button[2]");
  public static final By NOT_OB_COMPLETEQA_BUTTON = By.xpath("//*[@id=\"notOBNewCaseAdd\"]/div/div/div[3]/button[1]");
  public static final By POPUP_CONFIRM = By.xpath("//div[@class='modal-footer justify-content-center']//button[1]");
  public static final By CLOSE_MODEL =By.id("closeModal");
  // Create OB Case locators
  public static final By FIRST_NAME_OB = By.id("firstname");
  public static final By LAST_NAME_OB = By.id("lastname");
  public static final By GENDER_OB = By.id("gender");
  public static final By SITE_OB = By.id("site");
  public static final By FACILITY_OB_DROP = By.id("procedureLocationAddField");
  public static final By PROCEDURE_OB = By.id("procedure");
  public static final By SUB_PROCEDURE_OB = By.id("subProcedure");
  public static final By DOB_OB = By.id("dob");
  public static final By SAVE_BTN = By.id("saveButton");
  public static final By SAVE_AND_QA = By.id("actionButton");
  public static final By UPLOAD_RECORDS_BTN = By.id("uploadButton");
  //QAflow locators
  public static final By ADVERSE_YES = By.id("advisoryEventsValueYes");
  public static final By ADVERSE_NO = By.id("advisoryEventsValueNo");
  public static final By ADVERSE_EVENT_LIST = By.xpath("(//div[@class='text-center optionbox']//div)[2]");
  public static final By UPLOAD_PAGE = By.id("uploadfile");

  public static final By DOCUMENT_EMERGENCY_YES = By.id("obFlowDocumentEmergencyYes");
  public static final By DOCUMENT_EMERGENCY_NO = By.id("obFlowDocumentEmergencyNo");

  //batch quality case
  public static final By Case_Quality = By.xpath("//tbody[@id='multipleCaseOptionBody']//input[1]");
  public static final By QUALITY_COMPLETEQA = By.id("multipleSelectedCasesButton");
  public static final By QA_BACK_BTN = By.xpath("//*[@id=\"documentEmergencyShow\"]/div/div[2]/div/div[2]/div/div/button");
}